.PHONY: verify test

verify:
	python3 -m pytest -q tests/test_shadow_of_infinity_scope_lock.py tests/test_shadow_of_infinity_completion_2026_04_13.py tests/test_shadow_of_infinity_registry_returns_values.py tests/test_shadow_of_infinity_against_toolkit_and_clay_registry.py

test:
	python3 -m pytest -q tests/test_shadow_of_infinity_scope_lock.py tests/test_shadow_of_infinity_completion_2026_04_13.py tests/test_shadow_of_infinity_registry_returns_values.py tests/test_shadow_of_infinity_against_toolkit_and_clay_registry.py
